import json

# Load the notebook
with open('notebooks/task2_sql.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

for cell in notebook['cells']:
    if cell['cell_type'] == 'code':
        source_str = "".join(cell['source'])
        
        # 1. Update Query 11 (QUALIFY error handling)
        if "QUALIFY RankInCountry <= 3" in source_str:
            new_source = [
                "try:\n",
                "    display(run_query(\"\"\"\n",
                "        WITH ProductRevenue AS (\n",
                "            SELECT \n",
                "                Country,\n",
                "                Description,\n",
                "                ROUND(SUM(TotalPrice), 2) AS Revenue\n",
                "            FROM orders\n",
                "            GROUP BY Country, Description\n",
                "        )\n",
                "        SELECT *,\n",
                "            ROW_NUMBER() OVER (\n",
                "                PARTITION BY Country \n",
                "                ORDER BY Revenue DESC\n",
                "            ) AS RankInCountry\n",
                "        FROM ProductRevenue\n",
                "        WHERE Country IN ('United Kingdom', 'Germany', 'France')\n",
                "        QUALIFY RankInCountry <= 3\n",
                "    \"\"\"))\n",
                "except Exception as e:\n",
                "    print(f\"[ERROR] SQLite standard does not support QUALIFY directly:\")\n",
                "    print(f\"  {e}\")\n",
                "    print(\"Note: QUALIFY is supported in analytical engines like BigQuery and Snowflake.\")\n",
                "    print(\"Please run the SQLite-compatible alternative below instead!\")"
            ]
            cell['source'] = new_source
            print("Updated Query 11 (QUALIFY)")
            
        # 2. Update Query 6 (Day of the week logic)
        elif "GROUP BY Day" in source_str or "DayOfWeek" in source_str:
            new_source = [
                "q6 = query(\"\"\"\n",
                "    SELECT \n",
                "        CASE CAST(strftime('%w', InvoiceDate) AS INTEGER)\n",
                "            WHEN 0 THEN 'Sunday'\n",
                "            WHEN 1 THEN 'Monday'\n",
                "            WHEN 2 THEN 'Tuesday'\n",
                "            WHEN 3 THEN 'Wednesday'\n",
                "            WHEN 4 THEN 'Thursday'\n",
                "            WHEN 5 THEN 'Friday'\n",
                "            WHEN 6 THEN 'Saturday'\n",
                "        END AS DayOfWeek,\n",
                "        COUNT(DISTINCT InvoiceNo)      AS TotalOrders,\n",
                "        ROUND(SUM(TotalPrice), 2)      AS TotalRevenue,\n",
                "        ROUND(AVG(TotalPrice), 2)      AS AvgOrderValue\n",
                "    FROM orders\n",
                "    GROUP BY DayOfWeek\n",
                "    ORDER BY TotalRevenue DESC\n",
                "\"\"\")\n",
                "\n",
                "print('💡 Q6: Best Day of the Week for Sales')\n",
                "display(q6)"
            ]
            cell['source'] = new_source
            print("Updated Query 6 (Day of Week)")
            
        # 3. Update SQL queries saving block
        elif "with open('../scripts/task2_queries.sql'" in source_str:
            new_source = [
                "import os\n",
                "os.makedirs('../scripts', exist_ok=True)\n",
                "\n",
                "sql_content = \"\"\"\n",
                "-- ============================================================\n",
                "-- ApexPlanet Data Analytics Internship — Task 2\n",
                "-- SQL Queries for E-commerce Data Extraction\n",
                "-- ============================================================\n",
                "\n",
                "-- Q1: Top 5 Products by Revenue\n",
                "SELECT Description, ROUND(SUM(TotalPrice),2) AS Revenue\n",
                "FROM orders GROUP BY Description\n",
                "ORDER BY Revenue DESC LIMIT 5;\n",
                "\n",
                "-- Q2: Monthly Sales Trend\n",
                "SELECT Year, Month, ROUND(SUM(TotalPrice),2) AS MonthlyRevenue\n",
                "FROM orders GROUP BY Year, Month ORDER BY Year, Month;\n",
                "\n",
                "-- Q3: Top 10 Customers by Spend\n",
                "SELECT CustomerID, Country, ROUND(SUM(TotalPrice),2) AS TotalSpend,\n",
                "       COUNT(DISTINCT InvoiceNo) AS TotalOrders\n",
                "FROM orders GROUP BY CustomerID ORDER BY TotalSpend DESC LIMIT 10;\n",
                "\n",
                "-- Q4: Customer Segmentation by Spend\n",
                "WITH CustomerSpend AS (\n",
                "    SELECT CustomerID, SUM(TotalPrice) AS TotalSpend\n",
                "    FROM orders GROUP BY CustomerID\n",
                ")\n",
                "SELECT\n",
                "    CASE\n",
                "        WHEN TotalSpend >= 5000 THEN 'High Value'\n",
                "        WHEN TotalSpend >= 1000 THEN 'Mid Value'\n",
                "        WHEN TotalSpend >= 200  THEN 'Low Value'\n",
                "        ELSE 'Occasional'\n",
                "    END AS Segment,\n",
                "    COUNT(*) AS CustomerCount,\n",
                "    ROUND(SUM(TotalSpend),2) AS SegmentRevenue\n",
                "FROM CustomerSpend GROUP BY Segment ORDER BY SegmentRevenue DESC;\n",
                "\n",
                "-- Q5: Top 10 Countries by Revenue\n",
                "SELECT Country, ROUND(SUM(TotalPrice),2) AS Revenue,\n",
                "       COUNT(DISTINCT CustomerID) AS Customers\n",
                "FROM orders GROUP BY Country ORDER BY Revenue DESC LIMIT 10;\n",
                "\n",
                "-- Q6: Best Day of the Week for Sales\n",
                "SELECT \n",
                "    CASE CAST(strftime('%w', InvoiceDate) AS INTEGER)\n",
                "        WHEN 0 THEN 'Sunday'\n",
                "        WHEN 1 THEN 'Monday'\n",
                "        WHEN 2 THEN 'Tuesday'\n",
                "        WHEN 3 THEN 'Wednesday'\n",
                "        WHEN 4 THEN 'Thursday'\n",
                "        WHEN 5 THEN 'Friday'\n",
                "        WHEN 6 THEN 'Saturday'\n",
                "    END AS DayOfWeek,\n",
                "    COUNT(DISTINCT InvoiceNo)      AS TotalOrders,\n",
                "    ROUND(SUM(TotalPrice), 2)      AS TotalRevenue,\n",
                "    ROUND(AVG(TotalPrice), 2)      AS AvgOrderValue\n",
                "FROM orders\n",
                "GROUP BY DayOfWeek\n",
                "ORDER BY TotalRevenue DESC;\n",
                "\n",
                "-- Q7: Average Order Value per Country\n",
                "SELECT \n",
                "    Country,\n",
                "    ROUND(AVG(OrderTotal), 2)   AS AvgOrderValue,\n",
                "    COUNT(*)                    AS TotalOrders\n",
                "FROM (\n",
                "    SELECT \n",
                "        Country,\n",
                "        InvoiceNo,\n",
                "        SUM(TotalPrice) AS OrderTotal\n",
                "    FROM orders\n",
                "    GROUP BY Country, InvoiceNo\n",
                ")\n",
                "GROUP BY Country\n",
                "HAVING TotalOrders >= 10\n",
                "ORDER BY AvgOrderValue DESC\n",
                "LIMIT 10;\n",
                "\n",
                "-- Q8: Products Ordered Only Once (No Repeat Orders)\n",
                "SELECT \n",
                "    Description,\n",
                "    COUNT(DISTINCT InvoiceNo)  AS TimesOrdered,\n",
                "    SUM(Quantity)              AS TotalQtySold,\n",
                "    ROUND(SUM(TotalPrice), 2)  AS TotalRevenue\n",
                "FROM orders\n",
                "GROUP BY Description\n",
                "HAVING TimesOrdered = 1\n",
                "ORDER BY TotalRevenue DESC\n",
                "LIMIT 10;\n",
                "\n",
                "-- Q9: Month-over-Month Growth (Window Function)\n",
                "WITH MonthlyRev AS (\n",
                "    SELECT Year, Month, ROUND(SUM(TotalPrice),2) AS Revenue\n",
                "    FROM orders GROUP BY Year, Month\n",
                ")\n",
                "SELECT Year, Month, Revenue,\n",
                "    LAG(Revenue) OVER (ORDER BY Year, Month) AS PrevRevenue,\n",
                "    ROUND((Revenue - LAG(Revenue) OVER (ORDER BY Year, Month))\n",
                "        / LAG(Revenue) OVER (ORDER BY Year, Month) * 100, 2) AS GrowthPct\n",
                "FROM MonthlyRev ORDER BY Year, Month;\n",
                "\n",
                "-- Q10: Revenue Share by Product Price Category\n",
                "WITH ProductRevenue AS (\n",
                "    SELECT \n",
                "        Description,\n",
                "        UnitPrice,\n",
                "        ROUND(SUM(TotalPrice), 2) AS TotalRevenue\n",
                "    FROM orders\n",
                "    GROUP BY Description, UnitPrice\n",
                ")\n",
                "SELECT \n",
                "    CASE \n",
                "        WHEN UnitPrice >= 10 THEN 'Premium (>=£10)'\n",
                "        WHEN UnitPrice >= 3  THEN 'Mid-Range (£3–£9.99)'\n",
                "        ELSE 'Budget (<£3)'\n",
                "    END AS PriceCategory,\n",
                "    COUNT(*)                        AS ProductCount,\n",
                "    ROUND(SUM(TotalRevenue), 2)     AS TotalRevenue,\n",
                "    ROUND(AVG(TotalRevenue), 2)     AS AvgRevPerProduct\n",
                "FROM ProductRevenue\n",
                "GROUP BY PriceCategory\n",
                "ORDER BY TotalRevenue DESC;\n",
                "\"\"\"\n",
                "\n",
                "with open('../scripts/task2_queries.sql', 'w') as f:\n",
                "    f.write(sql_content)\n",
                "\n",
                "print('✅ SQL queries saved to scripts/task2_queries.sql')\n"
            ]
            cell['source'] = new_source
            print("Updated Step 10 (Save Queries)")

# Save the notebook back
with open('notebooks/task2_sql.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("[OK] Notebook successfully updated and written.")
